<?php
/*
 * Pipedrive
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pipedrive\Models;

use JsonSerializable;

/**
 *The additional data in the Role
 */
class AdditionalData2 implements JsonSerializable
{
    /**
     * The settings for the Role
     * @var \Pipedrive\Models\RoleSettings|null $settings public property
     */
    public $settings;

    /**
     * Constructor to set initial or default values of member properties
     * @param RoleSettings $settings Initialization value for $this->settings
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->settings = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['settings'] = $this->settings;

        return $json;
    }
}
