<?php
/*
 * Pipedrive
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pipedrive\Models;

/**
 * The item type
 */
class ItemTypeEnum
{
    /**
     * TODO: Write general description for this element
     */
    const DEAL = "deal";

    /**
     * TODO: Write general description for this element
     */
    const ORGANIZATION = "organization";

    /**
     * TODO: Write general description for this element
     */
    const PERSON = "person";
}
