<?php
/*
 * Pipedrive
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pipedrive\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class Pipeline implements JsonSerializable
{
    /**
     * Name of the pipeline
     * @var string|null $name public property
     */
    public $name;

    /**
     * @todo Write general description for this property
     * @maps deal_probability
     * @var int|null $dealProbability public property
     */
    public $dealProbability;

    /**
     * Defines pipelines order. First order(order_nr=0) is the default pipeline.
     * @maps order_nr
     * @var integer|null $orderNr public property
     */
    public $orderNr;

    /**
     * @todo Write general description for this property
     * @var int|null $active public property
     */
    public $active;

    /**
     * Constructor to set initial or default values of member properties
     * @param string  $name            Initialization value for $this->name
     * @param int     $dealProbability Initialization value for $this->dealProbability
     * @param integer $orderNr         Initialization value for $this->orderNr
     * @param int     $active          Initialization value for $this->active
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->name            = func_get_arg(0);
            $this->dealProbability = func_get_arg(1);
            $this->orderNr         = func_get_arg(2);
            $this->active          = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']             = $this->name;
        $json['deal_probability'] = $this->dealProbability;
        $json['order_nr']         = $this->orderNr;
        $json['active']           = $this->active;

        return $json;
    }
}
