<?php
/*
 * Pipedrive
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace Pipedrive\Models;

use JsonSerializable;

/**
 * @todo Write general description for this model
 */
class UserAssignmentToPermissionSet implements JsonSerializable
{
    /**
     * The ID of the assignment of the Permission Set
     * @var integer|null $id public property
     */
    public $id;

    /**
     * The ID of the User in the Permission Set
     * @maps user_id
     * @var integer|null $userId public property
     */
    public $userId;

    /**
     * The ID of the Permission Set
     * @maps permission_set_id
     * @var integer|null $permissionSetId public property
     */
    public $permissionSetId;

    /**
     * The name of the Permission Set
     * @var string|null $name public property
     */
    public $name;

    /**
     * Constructor to set initial or default values of member properties
     * @param integer $id              Initialization value for $this->id
     * @param integer $userId          Initialization value for $this->userId
     * @param integer $permissionSetId Initialization value for $this->permissionSetId
     * @param string  $name            Initialization value for $this->name
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->id              = func_get_arg(0);
            $this->userId          = func_get_arg(1);
            $this->permissionSetId = func_get_arg(2);
            $this->name            = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['id']                = $this->id;
        $json['user_id']           = $this->userId;
        $json['permission_set_id'] = $this->permissionSetId;
        $json['name']              = $this->name;

        return $json;
    }
}
